### ISSUE TITLE
apt-update fails when building environment with vagrant

### ISSUE THREAD

**Issue by ejiblabahaba** [rbewley4/ep-character-creator#49]
As of July, saucy is no longer supported on apt.puppetlabs.com, see https://groups.google.com/forum/#!topic/puppet-dev/jWvnE688bD4; as such apt-update fails since there's no repo to pull from.

**Comment by rbewley4** [comment]
Those guys at puppet labs are a bunch of jerks for removing those packages. I reverted back to the previous Ubuntu release in order to get it working again. Try it now.

**Comment by ejiblabahaba** [comment]
Up and running now. Thanks for the quick fix!
