### ISSUE TITLE
Skill specializations break PDF formatting

### ISSUE THREAD

**Issue by kauffmanelia** [rbewley4/ep-character-creator#67]
<img width="419" alt="screen shot 2015-11-30 at 12 25 38 am" src="https://cloud.githubusercontent.com/assets/7381895/11466834/efc0cc98-96f8-11e5-8d76-8aab4f983ad4.png">

Skill specializations are overlaid over the parent skill and a big gap is left beneath.

**Comment by EmperorArthur** [comment]
Does this happen if you use Pull #66?
That includes some fairly significant changes to the export code.
It also simplifies setting up a local copy to play with (all you need is PHP and sqlite3).

**Comment by kauffmanelia** [comment]
I'm using the online version here: http://eclipsephase.oook.ch/Creator/version4/index.php. How would I get at the new version?

**Comment by FullSimplex** [comment]
That not the Pull #66. I take note but have not the time right now to merge / or correct the bug on eclipsephase.ook.ch sorry :) 

@EmperorArthur Is the Pull #66 tested ? can i merge and put it online ?

**Comment by EmperorArthur** [comment]
Let me change the commit order around so it's a bit clearer what's going on.
Shouldn't take long.

**Comment by EmperorArthur** [comment]
Ok, I've gone over the commits, but decided not to change anything.  I've tested it, and it does work.
It's ready to merge!

One big thing I need to point out is you're going to need to modify your src/php/config.ini

**Comment by EmperorArthur** [comment]
Please try this version, and let me know if the problem persists:

https://www.cd-net.net/ep-character-creator/src/Creator/version4/index.php

**Comment by kauffmanelia** [comment]
Appears solved in that version.

**Comment by EmperorArthur** [comment]
Issue is solved in master.
