### ISSUE TITLE
Hosting change and testing

### ISSUE THREAD

**Issue by FullSimplex** [rbewley4/ep-character-creator#70]
Hi,

I move my stuff from oook.ch to next-loop.com

The last version of the eclipse phase creator is on eclipsephase.next-loop.com

If any of you have time, can you test this version and tell me if it work properly ? 
(before I erase the oook.ch version)

Tanks in advance  :)

**Comment by rbewley4** [comment]
Hi Cédric,

I have been out of the loop for a while, so I am not sure that I am the best person to carry out the testing; however, I will try to test it sometime this weekend.

Regards,

Russell

**Comment by rbewley4** [comment]
Hi Cédric,

I tested out the new site, http://eclipsephase.next-loop.com <http://eclipsephase.next-loop.com/>, but it does not work very well. The site seems to suffer from very high latency. Clicking on many of the navigation items often results in a 1.5 - 2 minute wait before the menu is displayed.

**Comment by FullSimplex** [comment]
Hi, tanks for testing. :)

I cannot replicate the problem, all the navigation items seem to appear normally and instantly.

Have you clean your cookies ?
Is the problem always present or just some time ?


Cedric Reinhardt
-----------------------
0041(0)78 608 2345
-----------------------
reinhardt@next-loop.com

**Comment by rbewley4** [comment]
I just ran a traceroute to eclipsephase.next-loop.com <http://eclipsephase.next-loop.com/> and discovered that it takes 17 hops for me to get to that server, and many of the hops take 150+ ms. That explains the latency for me. You must be much closer to the server.

**Comment by FullSimplex** [comment]
Well,

For me it takes 13 hops (10 - 60 ms)

oook was in Switzerland and next-loop is in Amsterdam. 

Have you the same problem with oook ?

The dns was set Friday, maybe the propagation is not optimal yet ?


Cedric Reinhardt
-----------------------
0041(0)78 608 2345
-----------------------
reinhardt@next-loop.com

**Comment by rbewley4** [comment]
oook.ch is much faster for me.

**Comment by EmperorArthur** [comment]
Not seeing any noticeable speed difference from Comcast in North America.

**Comment by FullSimplex** [comment]
oook.ch is no more on line.
eclipsephase.next-loop.com
