### ISSUE TITLE
 Access permissions

### ISSUE THREAD

**Issue by FullSimplex** [rbewley4/ep-character-creator#83]
I do not find the e-mail  of @rbewley4  and @EmperorArthur so i put this message on the issues board.

@rbewley4 is it possible to give @EmperorArthur the right  access permissions so he can manage the repository ? (he is the only one working on this repo for the moment.)

@EmperorArthur  Thanks for the work :)

**Comment by rbewley4** [comment]
I am having some issues logging into GitHub right now, so I cannot grant access just yet; however, I believe that I gave you owner permissions, so you should also be able to grant access to the repository in my stead.

**Comment by FullSimplex** [comment]
Hélas, i can merge pull request but i can not access the settings of the repository.

**Comment by rbewley4** [comment]
Ok, I was able to login. I have added @EmperorArthur as a collaborator. Hopefully that grants him enough privileges. Let me know if you need anything else.

**Comment by FullSimplex** [comment]
Thanks 👍

**Comment by EmperorArthur** [comment]
Thanks!!!
