### ISSUE TITLE
Can not add new fields for knowledge skills in Chrome

### ISSUE THREAD

**Issue by TrevorMassey** [rbewley4/ep-character-creator#90]
When I try to add a new field for Academics, Interest, Profession, etc., in the knowledge skills section, I always get the same error message: "Attempting to add a blank skill!"

The "Primary Language" field works as expected, and I can add new Active Skill fields for Hardware and Piloting. It only seems to affect Knowledge Skills.
![untitled](https://cloud.githubusercontent.com/assets/25093722/24179108/5322e408-0e6a-11e7-864a-3eeb8c4b6789.png)

**Comment by EmperorArthur** [comment]
Thanks for letting me know about this.

Fixed in Pull #91.

The fix is now live, so feel free to play around some more.
